"""Not using api key for group

Revision ID: 2227c2a3c7e8
Revises: 1df10436383f
Create Date: 2015-09-06 14:55:08.451869

"""

# revision identifiers, used by Alembic.
revision = '2227c2a3c7e8'
down_revision = '1df10436383f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'api_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('api_key', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
