"""Initial migration

Revision ID: 1d93852b0c2
Revises: None
Create Date: 2015-09-07 13:40:06.588930

"""

# revision identifiers, used by Alembic.
revision = '1d93852b0c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('gpg_pubkey_id', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('remote_repository_url', sa.String(), nullable=True),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('repository_type', sa.Enum('repository_dependency', 'tool', 'suite', 'viz', 'interactive_environment'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('tar_gz_sha256', sa.String(length=64), nullable=False),
    sa.Column('tar_gz_sig_available', sa.Boolean(), nullable=False),
    sa.Column('replacement_revision', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['replacement_revision'], ['revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('api_key', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('gpg_pubkey_id', sa.String(length=16), nullable=True),
    sa.Column('github', sa.String(length=32), nullable=True),
    sa.Column('github_username', sa.String(length=64), nullable=True),
    sa.Column('github_repos_url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github')
    )
    op.create_table('installable_group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('installable_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['installable_id'], ['installable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installable_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('installable_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installable_id'], ['installable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('revisions',
    sa.Column('installable_id', sa.Integer(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installable_id'], ['installable.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], )
    )
    op.create_table('suite_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=False),
    sa.Column('installable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installable'], ['installable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('installable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installable_id'], ['installable.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('suiterevision_revision',
    sa.Column('suiterevision_id', sa.Integer(), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['suiterevision_id'], ['suite_revision.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suiterevision_revision')
    op.drop_table('tags')
    op.drop_table('suite_revision')
    op.drop_table('revisions')
    op.drop_table('members')
    op.drop_table('installable_user_permissions')
    op.drop_table('installable_group_permissions')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('revision')
    op.drop_table('installable')
    op.drop_table('group')
    ### end Alembic commands ###
