"""empty message

Revision ID: 20aaddf62294
Revises: 293e110a48f6
Create Date: 2015-09-07 18:33:28.440317

"""

# revision identifiers, used by Alembic.
revision = '20aaddf62294'
down_revision = '293e110a48f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_adjacency',
    sa.Column('from_revision_id', sa.Integer(), nullable=True),
    sa.Column('to_revision_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_revision_id'], ['revision.id'], ),
    sa.ForeignKeyConstraint(['to_revision_id'], ['revision.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_adjacency')
    ### end Alembic commands ###
