# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField()),
                ('website', models.TextField()),
                ('gpg_pubkey_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Installable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('synopsis', models.TextField()),
                ('description', models.TextField()),
                ('remote_repository_url', models.TextField()),
                ('homepage_url', models.TextField()),
                ('repository_type', models.IntegerField(choices=[(0, b'tool'), (1, b'datatype'), (2, b'suite'), (3, b'viz'), (4, b'gie')])),
                ('group_access', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12)),
                ('commit_message', models.TextField()),
                ('uploaded', models.DateTimeField()),
                ('tar_gz_sha256', models.CharField(max_length=64)),
                ('tar_gz_sig_available', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_revision', to='base.Revision')),
                ('to_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_revision', to='base.Revision')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12)),
                ('commit_message', models.TextField()),
                ('contained_revisions', models.ManyToManyField(to='base.Revision')),
                ('installable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Installable')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('api_key', models.CharField(blank=True, max_length=32, unique=True)),
                ('gpg_pubkey_id', models.CharField(max_length=16)),
                ('github', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='used_in', through='base.RevisionDependency', to='base.Revision'),
        ),
        migrations.AddField(
            model_name='revision',
            name='installable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Installable'),
        ),
        migrations.AddField(
            model_name='revision',
            name='replacement_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Revision'),
        ),
        migrations.AddField(
            model_name='installable',
            name='tags',
            field=models.ManyToManyField(to='base.Tag'),
        ),
        migrations.AddField(
            model_name='installable',
            name='user_access',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
