# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDependencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, b'conda')])),
                ('identifier', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='package_dependencies',
            field=models.ManyToManyField(to='base.PackageDependencies'),
        ),
    ]
