# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20151223_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageDependencies',
            new_name='PackageDependency',
        ),
    ]
