# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_installable_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12)),
                ('commit_message', models.TextField()),
                ('uploaded', models.DateTimeField()),
                ('tar_gz_sha256', models.CharField(max_length=64)),
                ('tar_gz_sig_available', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VersionDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_version', to='base.Version')),
                ('to_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_version', to='base.Version')),
            ],
        ),
        migrations.RenameModel(
            old_name='SuiteRevision',
            new_name='SuiteVersion',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='installable',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='package_dependencies',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='replacement_revision',
        ),
        migrations.RemoveField(
            model_name='revisiondependency',
            name='from_revision',
        ),
        migrations.RemoveField(
            model_name='revisiondependency',
            name='to_revision',
        ),
        migrations.AlterModelOptions(
            name='packagedependency',
            options={'verbose_name_plural': 'Package dependencies'},
        ),
        migrations.RenameField(
            model_name='packagedependency',
            old_name='version',
            new_name='package_version',
        ),
        migrations.RemoveField(
            model_name='suiteversion',
            name='contained_revisions',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
        migrations.DeleteModel(
            name='RevisionDependency',
        ),
        migrations.AddField(
            model_name='version',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='used_in', through='base.VersionDependency', to='base.Version'),
        ),
        migrations.AddField(
            model_name='version',
            name='installable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Installable'),
        ),
        migrations.AddField(
            model_name='version',
            name='package_dependencies',
            field=models.ManyToManyField(to='base.PackageDependency'),
        ),
        migrations.AddField(
            model_name='version',
            name='replacement_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_to', to='base.Version'),
        ),
        migrations.AddField(
            model_name='suiteversion',
            name='contained_versions',
            field=models.ManyToManyField(to='base.Version'),
        ),
    ]
