# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20151223_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installable',
            name='homepage_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='installable',
            name='remote_repository_url',
            field=models.URLField(),
        ),
    ]
