# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160316_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='changeset_revision',
            field=models.CharField(default='', editable=False, max_length=12),
            preserve_default=False,
        ),
    ]
